heat_template_version: 2014-10-16
description: A server claiming a fixed IP
parameters:
  image:
    type: string
    description: Image used for servers
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
  user_data:
    type: string
    description: Server user_data
  metadata:
    type: json
  network:
    type: string
    description: Network used by the server
  ip:
    type: string
    description: Floating IP to claim

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      user_data: {get_param: user_data}
      networks:
        - port: { get_resource: port }
  port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network}
      security_groups:
        - Main server
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: {get_param: ip}
      server_id: { get_resource: server }

outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [server, first_address] }
